### ISSUE TITLE
Undefined array key

### ISSUE THREAD

**Issue by nibreh** [makefu/tw-upload-plugin#1]
Hello

I got some errors when upload with password, since php version 8 :
`Warning Undefined array key 1 on line 270`
`Warning Undefined array key "debug"  on line 275`

Could you please help me ?

Thanks !

**Comment by makefu** [comment]
Hi!
unfortunately i have no idea about the code, i just patched out some security issues. Sorry!
If you get it running, be sure to get back here or maybe even create a PR!
cheers

**Comment by nibreh** [comment]
I create issue here :
https://github.com/Jermolene/TiddlyWiki5/issues/6472

I'm not a programmer, so I upload Tiddlywiki with filezilla for now.

Thanks

**Comment by makefu** [comment]
Thanks for the report anyway!
